### ISSUE TITLE
markdown 使用问题建议

### ISSUE THREAD

**Issue by pankui** [gqwzi/gaozi-study-note#1]
1、shell 脚本没有高亮，说明markdown 使用有问题。

2、排版太差了

3、.idea 等这些不要上传

**Comment by gqwzi** [comment]
😂知道啦～3Q！

**Comment by pankui** [comment]
那就关闭

**Comment by gqwzi** [comment]
666～这咋还给我发邮件呢🌚


| |
高强伟
邮箱：15364917905@163.com
|

签名由 网易邮箱大师 定制

在2019年01月25日 23:12，pankui 写道：

那就关闭
